# Copyright 2025 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is configuration for efm-langserver. For more information on the file
# format, see:
# https://github.com/mattn/efm-langserver/blob/master/schema.md

version: 2
# NOTE: efm-langserver does not support substitutions in the configuration
# file. Substitutions like ${XDG_CONFIG_HOME} are made by the Makefile upon
# installation.
log-file: ${XDG_CONFIG_HOME}/efm-langserver/efm-langserver.log
log-level: 1
